### ISSUE TITLE
NLU not working when using "botonic train"

### ISSUE THREAD

**Issue by Larox** [hubtype/botonic#2303]
**Describe the bug**
I'm following the steps from the [docs to implement NLU](https://botonic.io/docs/plugins/plugin-nlu/). When running `botonic train` I get this outcome:

```bash
$ botonic train

> blank@1.0.0 train:ner /Users/sarias/Documents/WORK/instantbuy-chatbot/instanbuyChatBot
> ts-node src/nlp/tasks/ner/train.ts


> blank@1.0.0 train:intent-classification /Users/sarias/Documents/WORK/instantbuy-chatbot/instanbuyChatBot
> ts-node src/nlp/tasks/intent-classification/train.ts

internal/modules/cjs/loader.js:892
  throw err;
  ^

Error: Cannot find module './train.ts'
Require stack:
- /Users/sarias/Documents/WORK/instantbuy-chatbot/instanbuyChatBot/src/nlp/tasks/ner/imaginaryUncacheableRequireResolveScript
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
    at Function.resolve (internal/modules/cjs/helpers.js:98:19)
    at requireResolveNonCached (/Users/sarias/Documents/WORK/instantbuy-chatbot/instanbuyChatBot/node_modules/ts-node/dist/bin.js:549:16)
    at getProjectSearchDir (/Users/sarias/Documents/WORK/instantbuy-chatbot/instanbuyChatBot/node_modules/ts-node/dist/bin.js:519:40)
    at phase3 (/Users/sarias/Documents/WORK/instantbuy-chatbot/instanbuyChatBot/node_modules/ts-node/dist/bin.js:267:27)
    at bootstrap (/Users/sarias/Documents/WORK/instantbuy-chatbot/instanbuyChatBot/node_modules/ts-node/dist/bin.js:47:30)
    at main (/Users/sarias/Documents/WORK/instantbuy-chatbot/instanbuyChatBot/node_modules/ts-node/dist/bin.js:33:12)
    at Object.<anonymous> (/Users/sarias/Documents/WORK/instantbuy-chatbot/instanbuyChatBot/node_modules/ts-node/dist/bin.js:579:5)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/sarias/Documents/WORK/instantbuy-chatbot/instanbuyChatBot/src/nlp/tasks/ner/imaginaryUncacheableRequireResolveScript'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! blank@1.0.0 train:ner: `ts-node src/nlp/tasks/ner/train.ts`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the blank@1.0.0 train:ner script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/sarias/.npm/_logs/2023-02-16T18_35_21_002Z-debug.log
child process exited with code 12023-02-16 13:35:24.333102: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2023-02-16 13:35:24.382107: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x104b07d40 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2023-02-16 13:35:24.382128: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
/Users/sarias/Documents/WORK/instantbuy-chatbot/instanbuyChatBot/src/nlp/data/en
Dataset size: 0
Train set size: 0
Test set size: 0
Found 'glove-50d-en.db'.
(node:60319) UnhandledPromiseRejectionWarning: SqliteError: no such table: embeddings
    at Database.prepare (/Users/sarias/Documents/WORK/instantbuy-chatbot/instanbuyChatBot/node_modules/better-sqlite3/lib/methods/wrappers.js:5:21)
    at DatabaseStorage.<anonymous> (/Users/sarias/Documents/WORK/instantbuy-chatbot/instanbuyChatBot/node_modules/@botonic/nlp/src/embeddings/database/storage.ts:63:36)
    at step (/Users/sarias/Documents/WORK/instantbuy-chatbot/instanbuyChatBot/node_modules/@botonic/nlp/lib/embeddings/database/storage.js:33:23)
    at Object.next (/Users/sarias/Documents/WORK/instantbuy-chatbot/instanbuyChatBot/node_modules/@botonic/nlp/lib/embeddings/database/storage.js:14:53)
    at fulfilled (/Users/sarias/Documents/WORK/instantbuy-chatbot/instanbuyChatBot/node_modules/@botonic/nlp/lib/embeddings/database/storage.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:60319) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:60319) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
child process exited with code 0% 
```

**To Reproduce**
Steps to reproduce the behaviour:
1. Follow [NLU plugin docs](https://botonic.io/docs/plugins/plugin-nlu/)
2. Add data to the utterances files as explained in the docs
3. Run `botonic train`

**What is the expected behaviour?**
The model is trained and the intents from the chat can be used in the bot routes.

**About the environment**
Which versions of [**botonic** packages](https://github.com/hubtype/botonic/tree/master/packages), and which browser/OS or environment (development/production) are affected by this issue? Did this work in previous versions of [**botonic** packages](https://github.com/hubtype/botonic/tree/master/packages)? 

- Botonic Version and Node version: @botonic/cli/0.21.0 darwin-x64 node-v14.17.4
- Project scaffolding was done using: `botonic new <projectname> blank`
- utterances directory:
![image](https://user-images.githubusercontent.com/9751266/219458145-fd3c7e66-460d-4a6e-af4d-0b5af84ad461.png)

**Additional context**
Each file inside `utterances/en/`  Has more than 50 lines.

I've tried with `botonic new <myProject> nlu` and doesn't work either

**Comment by Larox** [comment]
I'm tagging @dpinol @vanbasten17 for visibility!  Thank you in advance!

**Comment by MohitBansal321** [comment]
try `npm install @botonic/plugin-nlp` instead of `npm install @botonic/plugin-nlu` 
because it is potentially deprecated  @Larox

**Comment by Larox** [comment]
Hi @MohitBansal321 Thanks for your response and suggestion! I came across that issue and tried installing it but got this error. I'm not sure if I'm missing something.

```bash
$ npm install @botonic/plugin-nlp
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@botonic%2fplugin-nlp - Not found
npm ERR! 404
npm ERR! 404  '@botonic/plugin-nlp@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/sarias/.npm/_logs/2023-02-17T15_10_38_982Z-debug.log

```

**Comment by matysikatwork** [comment]
@Larox I think the nlp module is installed as part of the `botonic new` command, but it's unclear from the documentation how it should work. FWIW, I haven't been able to get either `npm install @botonic/plugin-nlu` or `@botonic/plugin-nlp` to work.

**Comment by Larox** [comment]
I'm having the same experience so far @matysikatwork, did you come around with an alternative for having intents/nlu in your project?


I would really appreciate a suggestion for this :)

**Comment by matysikatwork** [comment]
> I'm having the same experience so far @matysikatwork, did you come around with an alternative for having intents/nlu in your project?
> 
> I would really appreciate a suggestion for this :)

I haven't yet, it seems like the options would be to dig into the intent-classification script to debug it or try out Botonic's DialogFlow plugin.

**Comment by jhenriqueax** [comment]
Have you guys find this bug? I'm having the same issue.

**Comment by Larox** [comment]
Hi @jhenriqueax, I haven't had the chance to review this issue lately. Not update or suggestion I can share unfortunatelly.

**Comment by vanbasten17** [comment]
Hi all! Sorry for the late response! We will take a closer look and try to abilitate again the models. By the way, you should use `botonic-plugin-intent-classification` and `botonic-plugin-ner`.
