### ISSUE TITLE
Implemented code on a React JS framework

### ISSUE THREAD

**Issue by flamecopper** [hubtype/botonic#2509]
Hi there,

I have implemented the code from the following to:
https://botonic.io/docs/deployment/standalone-js-bundle

to a react js framework:

`import React, { useEffect } from 'react';
import clsx from 'clsx';
import Botonic from './webchat.botonic.js';

export default function FooterLayout({ style, links, logo, copyright }) {
  useEffect(() => {
      Botonic.render(document.getElementById('root'));
 
  }, []); // Run the effect only once, equivalent to componentDidMount

  return (
    <footer className={clsx('footer', { 'footer--dark': style === 'dark' })}>
      <div className="container container-fluid">
        {links}
        {logo || copyright ? (
          <div className="footer__bottom text--center">
            {logo && <div className="margin-bottom--sm">{logo}</div>}
            {copyright}
          </div>
        ) : null}
      </div>

      <div id="root"></div>
    </footer>
  );
}
`

How can I suppress the chatevent error?

```
ERROR
Parsing for type: 'chatevent' not implemented.
    at MessageParsingFactory.parse (webpack-internal:///./src/theme/Footer/Layout/webchat.botonic.js:1:959722)
    at BotonicOutputParser.parseFromUserInput (webpack-internal:///./src/theme/Footer/Layout/webchat.botonic.js:1:960307)
    at ReactBot._callee$ (webpack-internal:///./src/theme/Footer/Layout/webchat.botonic.js:1:977789)
    at tryCatch (webpack-internal:///./src/theme/Footer/Layout/webchat.botonic.js:1:910245)
    at Generator.eval (webpack-internal:///./src/theme/Footer/Layout/webchat.botonic.js:1:912005)
    at Generator.eval [as next] (webpack-internal:///./src/theme/Footer/Layout/webchat.botonic.js:1:910751)
    at asyncGeneratorStep (webpack-internal:///./src/theme/Footer/Layout/webchat.botonic.js:1:949557)
    at _next (webpack-internal:///./src/theme/Footer/Layout/webchat.botonic.js:1:949799)
    at eval (webpack-internal:///./src/theme/Footer/Layout/webchat.botonic.js:1:949923)
    at new Promise (<anonymous>)
```

**Comment by asastre** [comment]
Hi @flamecopper!

This issue has already been solved in [this PR](https://github.com/hubtype/botonic/pull/2506). If you use the `0.22.0-alpha.1` verson (or higher) of `@botonic/core` you will get rid of this error.

**Comment by flamecopper** [comment]
Hi, sorry to bring this up again, how do I install this to make it work like botonic/cli, https://botonic.io/docs/getting-started/, I am following the guide here to make it work for me.

**Comment by flamecopper** [comment]
Is the following install method correct;

npm list -g
/root/.nvm/versions/node/v18.16.0/lib
├── @botonic/cli@0.21.3
├── @botonic/core@0.22.0-alpha.1
├── corepack@0.17.0
├── js-beautify@1.14.7
└── npm@9.5.1

**Comment by vanbasten17** [comment]
@flamecopper pleas, reach us trough Slack and we can help you quicker

**Comment by flamecopper** [comment]
> @flamecopper please, reach us trough Slack and we can help you quicker

Don’t have an @botonic.io email address?
Contact the workspace administrator at Botonic for an invitation.
