### ISSUE TITLE
Botonic Train Error

### ISSUE THREAD

**Issue by flamecopper** [hubtype/botonic#2513]
blank@1.0.0 train:intent-classification
> ts-node src/nlp/tasks/intent-classification/train.ts

> blank@1.0.0 train:ner
> ts-node src/nlp/tasks/ner/train.ts

node:internal/modules/cjs/loader:1078
  throw err;
  ^

Error: Cannot find module './train.ts'
Require stack:
- /home/osboxes/Desktop/myBot/src/nlp/tasks/ner/imaginaryUncacheableRequireResolveScript
    at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
    at Function.resolve (node:internal/modules/cjs/helpers:116:19)
    at requireResolveNonCached (/home/osboxes/Desktop/myBot/node_modules/ts-node/dist/bin.js:549:16)
    at getProjectSearchDir (/home/osboxes/Desktop/myBot/node_modules/ts-node/dist/bin.js:519:40)
    at phase3 (/home/osboxes/Desktop/myBot/node_modules/ts-node/dist/bin.js:267:27)
    at bootstrap (/home/osboxes/Desktop/myBot/node_modules/ts-node/dist/bin.js:47:30)
    at main (/home/osboxes/Desktop/myBot/node_modules/ts-node/dist/bin.js:33:12)
    at Object.<anonymous> (/home/osboxes/Desktop/myBot/node_modules/ts-node/dist/bin.js:579:5)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/osboxes/Desktop/myBot/src/nlp/tasks/ner/imaginaryUncacheableRequireResolveScript'
  ]
}

Node.js v18.16.0
child process exited with code 12023-05-31 02:20:57.637964: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2023-05-31 02:20:57.648982: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2803200000 Hz
2023-05-31 02:20:57.650280: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7ff57837fd40 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2023-05-31 02:20:57.650327: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
Dataset size: 0
Train set size: 0
Test set size: 0
Found 'glove-50d-en.db'.
/home/osboxes/Desktop/myBot/node_modules/better-sqlite3/lib/methods/wrappers.js:5
	return this[cppdb].prepare(sql, this, false);
                    ^
SqliteError: no such table: embeddings
    at Database.prepare (/home/osboxes/Desktop/myBot/node_modules/better-sqlite3/lib/methods/wrappers.js:5:21)
    at DatabaseStorage.<anonymous> (/home/osboxes/Desktop/myBot/node_modules/@botonic/nlp/src/embeddings/database/storage.ts:63:36)
    at step (/home/osboxes/Desktop/myBot/node_modules/@botonic/nlp/lib/embeddings/database/storage.js:33:23)
    at Object.next (/home/osboxes/Desktop/myBot/node_modules/@botonic/nlp/lib/embeddings/database/storage.js:14:53)
    at fulfilled (/home/osboxes/Desktop/myBot/node_modules/@botonic/nlp/lib/embeddings/database/storage.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'SQLITE_ERROR'
}

**Comment by vanbasten17** [comment]
`blank` template doesn't come with the `train.ts` file from the scratch. Please, take a look at https://github.com/hubtype/botonic-examples/tree/master/nlu-assistant example, there it should be declared. Moreover, we are currently working on enable the models for developers again, as they weren't used a lot.
