### ISSUE TITLE
botonic serve on working on my machine

### ISSUE THREAD

**Issue by JoelAvatar** [hubtype/botonic#2524]
**getting a bunch of error**
Anytime i run botonic serve i get this:

modules with errors 117 bytes [errors]
  ./node_modules/webpack-dev-server/client/index.js?protocol=ws%3A&hostname=0.0.0....(truncated) 39 bytes [built] [code generated] [1 error]
  ./node_modules/webpack/hot/dev-server.js 39 bytes [built] [code generated] [1 error]
  ./webpack-entries/dev-entry.js 39 bytes [built] [code generated] [1 error]

ERROR in ./node_modules/webpack-dev-server/client/index.js?protocol=ws%3A&hostname=0.0.0.0&port=8080&pathname=%2Fws&logging=info&overlay=true&reconnect=10&hot=true&live-reload=true
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: Cannot find package '@babel/plugin-proposal-object-rest-spread' imported from C:\Users\USER\OneDrive\Desktop\myBoty\babel-virtual-resolve-base.js
    at new NodeError (C:\Users\USER\OneDrive\Desktop\myBoty\node_modules\@babel\core\lib\vendor\import-meta-resolve.js:203:5)
    at packageResolve (C:\Users\USER\OneDrive\Desktop\myBoty\node_modules\@babel\core\lib\vendor\import-meta-resolve.js:873:9)
    at moduleResolve (C:\Users\USER\OneDrive\Desktop\myBoty\node_modules\@babel\core\lib\vendor\import-meta-resolve.js:902:20)
    at defaultResolve (C:\Users\USER\OneDrive\Desktop\myBoty\node_modules\@babel\core\lib\vendor\import-meta-resolve.js:985:15)
    at resolve (C:\Users\USER\OneDrive\Desktop\myBoty\node_modules\@babel\core\lib\vendor\import-meta-resolve.js:999:12)
    at resolve (C:\Users\USER\OneDrive\Desktop\myBoty\node_modules\@babel\core\lib\config\files\import-meta-resolve.js:13:10)
    at tryImportMetaResolve (C:\Users\USER\OneDrive\Desktop\myBoty\node_modules\@babel\core\lib\config\files\plugins.js:137:45)
    at resolveStandardizedNameForImport (C:\Users\USER\OneDrive\Desktop\myBoty\node_modules\@babel\core\lib\config\files\plugins.js:159:19)
    at resolveStandardizedName (C:\Users\USER\OneDrive\Desktop\myBoty\node_modules\@babel\core\lib\config\files\plugins.js:168:12)
    at loadPlugin (C:\Users\USER\OneDrive\Desktop\myBoty\node_modules\@babel\core\lib\config\files\plugins.js:47:20)

ERROR in ./node_modules/webpack/hot/dev-server.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: Cannot find package '@babel/plugin-proposal-object-rest-spread' imported from C:\Users\USER\OneDrive\Desktop\myBoty\babel-virtual-resolve-base.js
    at new NodeError (C:\Users\USER\OneDrive\Desktop\myBoty\node_modules\@babel\core\lib\vendor\import-meta-resolve.js:203:5)
    at packageResolve (C:\Users\USER\OneDrive\Desktop\myBoty\node_modules\@babel\core\lib\vendor\import-meta-resolve.js:873:9)
    at moduleResolve (C:\Users\USER\OneDrive\Desktop\myBoty\node_modules\@babel\core\lib\vendor\import-meta-resolve.js:902:20)
    at defaultResolve (C:\Users\USER\OneDrive\Desktop\myBoty\node_modules\@babel\core\lib\vendor\import-meta-resolve.js:985:15)
    at resolve (C:\Users\USER\OneDrive\Desktop\myBoty\node_modules\@babel\core\lib\vendor\import-meta-resolve.js:999:12)
    at resolve (C:\Users\USER\OneDrive\Desktop\myBoty\node_modules\@babel\core\lib\config\files\import-meta-resolve.js:13:10)
    at tryImportMetaResolve (C:\Users\USER\OneDrive\Desktop\myBoty\node_modules\@babel\core\lib\config\files\plugins.js:137:45)
    at resolveStandardizedNameForImport (C:\Users\USER\OneDrive\Desktop\myBoty\node_modules\@babel\core\lib\config\files\plugins.js:159:19)
    at resolveStandardizedName (C:\Users\USER\OneDrive\Desktop\myBoty\node_modules\@babel\core\lib\config\files\plugins.js:168:12)
    at loadPlugin (C:\Users\USER\OneDrive\Desktop\myBoty\node_modules\@babel\core\lib\config\files\plugins.js:47:20)

ERROR in ./webpack-entries/dev-entry.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: Cannot find package '@babel/plugin-proposal-object-rest-spread' imported from C:\Users\USER\OneDrive\Desktop\myBoty\babel-virtual-resolve-base.js
    at new NodeError (C:\Users\USER\OneDrive\Desktop\myBoty\node_modules\@babel\core\lib\vendor\import-meta-resolve.js:203:5)
    at packageResolve (C:\Users\USER\OneDrive\Desktop\myBoty\node_modules\@babel\core\lib\vendor\import-meta-resolve.js:873:9)
    at moduleResolve (C:\Users\USER\OneDrive\Desktop\myBoty\node_modules\@babel\core\lib\vendor\import-meta-resolve.js:902:20)
    at defaultResolve (C:\Users\USER\OneDrive\Desktop\myBoty\node_modules\@babel\core\lib\vendor\import-meta-resolve.js:985:15)
    at resolve (C:\Users\USER\OneDrive\Desktop\myBoty\node_modules\@babel\core\lib\vendor\import-meta-resolve.js:999:12)
    at resolve (C:\Users\USER\OneDrive\Desktop\myBoty\node_modules\@babel\core\lib\config\files\import-meta-resolve.js:13:10)
    at tryImportMetaResolve (C:\Users\USER\OneDrive\Desktop\myBoty\node_modules\@babel\core\lib\config\files\plugins.js:137:45)
    at resolveStandardizedNameForImport (C:\Users\USER\OneDrive\Desktop\myBoty\node_modules\@babel\core\lib\config\files\plugins.js:159:19)
    at resolveStandardizedName (C:\Users\USER\OneDrive\Desktop\myBoty\node_modules\@babel\core\lib\config\files\plugins.js:168:12)
    at loadPlugin (C:\Users\USER\OneDrive\Desktop\myBoty\node_modules\@babel\core\lib\config\files\plugins.js:47:20)

webpack 5.86.0 compiled with 3 errors in 2625 ms

**Comment by JoelAvatar** [comment]
please help
